//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RahyabServices.ServiceTest.VipBankingRest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VipBankingRest.IVipBankingRestContract")]
    public interface IVipBankingRestContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVipBankingRestContract/GetAll", ReplyAction="http://tempuri.org/IVipBankingRestContract/GetAllResponse")]
        RahyabServices.Business.Dtos.VipBanking.AllVipDto GetAll(string key, string skip, string take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVipBankingRestContract/GetAll", ReplyAction="http://tempuri.org/IVipBankingRestContract/GetAllResponse")]
        System.Threading.Tasks.Task<RahyabServices.Business.Dtos.VipBanking.AllVipDto> GetAllAsync(string key, string skip, string take);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVipBankingRestContractChannel : RahyabServices.ServiceTest.VipBankingRest.IVipBankingRestContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VipBankingRestContractClient : System.ServiceModel.ClientBase<RahyabServices.ServiceTest.VipBankingRest.IVipBankingRestContract>, RahyabServices.ServiceTest.VipBankingRest.IVipBankingRestContract {
        
        public VipBankingRestContractClient() {
        }
        
        public VipBankingRestContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VipBankingRestContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VipBankingRestContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VipBankingRestContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RahyabServices.Business.Dtos.VipBanking.AllVipDto GetAll(string key, string skip, string take) {
            return base.Channel.GetAll(key, skip, take);
        }
        
        public System.Threading.Tasks.Task<RahyabServices.Business.Dtos.VipBanking.AllVipDto> GetAllAsync(string key, string skip, string take) {
            return base.Channel.GetAllAsync(key, skip, take);
        }
    }
}
