//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RahyabServices.Business.Facades.Sayad {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Sayad.SayadServicesSoap")]
    public interface SayadServicesSoap {
        
        // CODEGEN: Generating message contract since message GetChequeBookStatusByInquiryCodeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChequeBookStatusByInquiryCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RahyabServices.Business.Facades.Sayad.GetChequeBookStatusByInquiryCodeResponse GetChequeBookStatusByInquiryCode(RahyabServices.Business.Facades.Sayad.GetChequeBookStatusByInquiryCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChequeBookStatusByInquiryCode", ReplyAction="*")]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.GetChequeBookStatusByInquiryCodeResponse> GetChequeBookStatusByInquiryCodeAsync(RahyabServices.Business.Facades.Sayad.GetChequeBookStatusByInquiryCodeRequest request);
        
        // CODEGEN: Generating message contract since message GetListChequeBookStatusByChequeStatusTypeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListChequeBookStatusByChequeStatusType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RahyabServices.Business.Facades.Sayad.GetListChequeBookStatusByChequeStatusTypeResponse GetListChequeBookStatusByChequeStatusType(RahyabServices.Business.Facades.Sayad.GetListChequeBookStatusByChequeStatusTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListChequeBookStatusByChequeStatusType", ReplyAction="*")]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.GetListChequeBookStatusByChequeStatusTypeResponse> GetListChequeBookStatusByChequeStatusTypeAsync(RahyabServices.Business.Facades.Sayad.GetListChequeBookStatusByChequeStatusTypeRequest request);
        
        // CODEGEN: Generating message contract since message InsertChequeBookRequestRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertChequeBookRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RahyabServices.Business.Facades.Sayad.InsertChequeBookRequestResponse InsertChequeBookRequest(RahyabServices.Business.Facades.Sayad.InsertChequeBookRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertChequeBookRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.InsertChequeBookRequestResponse> InsertChequeBookRequestAsync(RahyabServices.Business.Facades.Sayad.InsertChequeBookRequestRequest request);
        
        // CODEGEN: Generating message contract since message UpdateAcceptInquiryRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAcceptInquiry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RahyabServices.Business.Facades.Sayad.UpdateAcceptInquiryResponse UpdateAcceptInquiry(RahyabServices.Business.Facades.Sayad.UpdateAcceptInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAcceptInquiry", ReplyAction="*")]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.UpdateAcceptInquiryResponse> UpdateAcceptInquiryAsync(RahyabServices.Business.Facades.Sayad.UpdateAcceptInquiryRequest request);
        
        // CODEGEN: Generating message contract since message UpdateRejectInquiryRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRejectInquiry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RahyabServices.Business.Facades.Sayad.UpdateRejectInquiryResponse UpdateRejectInquiry(RahyabServices.Business.Facades.Sayad.UpdateRejectInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRejectInquiry", ReplyAction="*")]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.UpdateRejectInquiryResponse> UpdateRejectInquiryAsync(RahyabServices.Business.Facades.Sayad.UpdateRejectInquiryRequest request);
        
        // CODEGEN: Generating message contract since message DeactivateBaseIBANRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeactivateBaseIBAN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RahyabServices.Business.Facades.Sayad.DeactivateBaseIBANResponse DeactivateBaseIBAN(RahyabServices.Business.Facades.Sayad.DeactivateBaseIBANRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeactivateBaseIBAN", ReplyAction="*")]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.DeactivateBaseIBANResponse> DeactivateBaseIBANAsync(RahyabServices.Business.Facades.Sayad.DeactivateBaseIBANRequest request);
        
        // CODEGEN: Generating message contract since message GetChequeAndDebtInquiryRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChequeAndDebtInquiry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RahyabServices.Business.Facades.Sayad.GetChequeAndDebtInquiryResponse GetChequeAndDebtInquiry(RahyabServices.Business.Facades.Sayad.GetChequeAndDebtInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChequeAndDebtInquiry", ReplyAction="*")]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.GetChequeAndDebtInquiryResponse> GetChequeAndDebtInquiryAsync(RahyabServices.Business.Facades.Sayad.GetChequeAndDebtInquiryRequest request);
        
        // CODEGEN: Generating message contract since message UpdateChangePasswordRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RahyabServices.Business.Facades.Sayad.UpdateChangePasswordResponse UpdateChangePassword(RahyabServices.Business.Facades.Sayad.UpdateChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.UpdateChangePasswordResponse> UpdateChangePasswordAsync(RahyabServices.Business.Facades.Sayad.UpdateChangePasswordRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonInquiryStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string returnedChequesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ReturnedCheques {
            get {
                return this.returnedChequesField;
            }
            set {
                this.returnedChequesField = value;
                this.RaisePropertyChanged("ReturnedCheques");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChequeInquiryStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iBANField;
        
        private PersonInquiryStatus[] accountOwnerInquiryStatusField;
        
        private double errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
                this.RaisePropertyChanged("IBAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public PersonInquiryStatus[] AccountOwnerInquiryStatus {
            get {
                return this.accountOwnerInquiryStatusField;
            }
            set {
                this.accountOwnerInquiryStatusField = value;
                this.RaisePropertyChanged("AccountOwnerInquiryStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("ErrorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExceptionFields : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double codeField;
        
        private string descriptionField;
        
        private string specific1Field;
        
        private string specific2Field;
        
        private string specific3Field;
        
        private string specific4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Specific1 {
            get {
                return this.specific1Field;
            }
            set {
                this.specific1Field = value;
                this.RaisePropertyChanged("Specific1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Specific2 {
            get {
                return this.specific2Field;
            }
            set {
                this.specific2Field = value;
                this.RaisePropertyChanged("Specific2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Specific3 {
            get {
                return this.specific3Field;
            }
            set {
                this.specific3Field = value;
                this.RaisePropertyChanged("Specific3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Specific4 {
            get {
                return this.specific4Field;
            }
            set {
                this.specific4Field = value;
                this.RaisePropertyChanged("Specific4");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SignatureOwnersDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string nameField;
        
        private int partyTypeField;
        
        private string identifierField;
        
        private IdentifierTypeList identifierTypeField;
        
        private string abisIdentifireTypeField;
        
        private string idNumField;
        
        private int birthDateField;
        
        private string cityCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PartyType {
            get {
                return this.partyTypeField;
            }
            set {
                this.partyTypeField = value;
                this.RaisePropertyChanged("PartyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public IdentifierTypeList IdentifierType {
            get {
                return this.identifierTypeField;
            }
            set {
                this.identifierTypeField = value;
                this.RaisePropertyChanged("IdentifierType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string AbisIdentifireType {
            get {
                return this.abisIdentifireTypeField;
            }
            set {
                this.abisIdentifireTypeField = value;
                this.RaisePropertyChanged("AbisIdentifireType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IdNum {
            get {
                return this.idNumField;
            }
            set {
                this.idNumField = value;
                this.RaisePropertyChanged("IdNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("CityCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum IdentifierTypeList {
        
        /// <remarks/>
        UnKnown,
        
        /// <remarks/>
        NationalCode,
        
        /// <remarks/>
        NationalID,
        
        /// <remarks/>
        ForeignID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountOwnersDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string nameField;
        
        private int partyTypeField;
        
        private string identifierField;
        
        private IdentifierTypeList identifierTypeField;
        
        private string abisIdentifireTypeField;
        
        private string idNumField;
        
        private int birthDateField;
        
        private string cityCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PartyType {
            get {
                return this.partyTypeField;
            }
            set {
                this.partyTypeField = value;
                this.RaisePropertyChanged("PartyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public IdentifierTypeList IdentifierType {
            get {
                return this.identifierTypeField;
            }
            set {
                this.identifierTypeField = value;
                this.RaisePropertyChanged("IdentifierType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string AbisIdentifireType {
            get {
                return this.abisIdentifireTypeField;
            }
            set {
                this.abisIdentifireTypeField = value;
                this.RaisePropertyChanged("AbisIdentifireType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IdNum {
            get {
                return this.idNumField;
            }
            set {
                this.idNumField = value;
                this.RaisePropertyChanged("IdNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
                this.RaisePropertyChanged("BirthDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
                this.RaisePropertyChanged("CityCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChequeBookRequestDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int printeryStatusField;
        
        private string requestCodeField;
        
        private SharedAccountTypes sharedAccountField;
        
        private string bankCodeField;
        
        private string branchCodeField;
        
        private string branchNameField;
        
        private string ownerBranchNameField;
        
        private string ownerBranchCodeField;
        
        private string iBANField;
        
        private int sheetCountField;
        
        private AccountOwnersDTO[] accountOwnersDTOField;
        
        private SignatureOwnersDTO[] signatureOwnersDTOField;
        
        private string postCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int PrinteryStatus {
            get {
                return this.printeryStatusField;
            }
            set {
                this.printeryStatusField = value;
                this.RaisePropertyChanged("PrinteryStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RequestCode {
            get {
                return this.requestCodeField;
            }
            set {
                this.requestCodeField = value;
                this.RaisePropertyChanged("RequestCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SharedAccountTypes SharedAccount {
            get {
                return this.sharedAccountField;
            }
            set {
                this.sharedAccountField = value;
                this.RaisePropertyChanged("SharedAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
                this.RaisePropertyChanged("BankCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("BranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BranchName {
            get {
                return this.branchNameField;
            }
            set {
                this.branchNameField = value;
                this.RaisePropertyChanged("BranchName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string OwnerBranchName {
            get {
                return this.ownerBranchNameField;
            }
            set {
                this.ownerBranchNameField = value;
                this.RaisePropertyChanged("OwnerBranchName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OwnerBranchCode {
            get {
                return this.ownerBranchCodeField;
            }
            set {
                this.ownerBranchCodeField = value;
                this.RaisePropertyChanged("OwnerBranchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
                this.RaisePropertyChanged("IBAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int SheetCount {
            get {
                return this.sheetCountField;
            }
            set {
                this.sheetCountField = value;
                this.RaisePropertyChanged("SheetCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public AccountOwnersDTO[] AccountOwnersDTO {
            get {
                return this.accountOwnersDTOField;
            }
            set {
                this.accountOwnersDTOField = value;
                this.RaisePropertyChanged("AccountOwnersDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public SignatureOwnersDTO[] SignatureOwnersDTO {
            get {
                return this.signatureOwnersDTOField;
            }
            set {
                this.signatureOwnersDTOField = value;
                this.RaisePropertyChanged("SignatureOwnersDTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("PostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SharedAccountTypes {
        
        /// <remarks/>
        UnShared,
        
        /// <remarks/>
        Shared,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChequeBookStatusDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestCodeField;
        
        private string shebaaField;
        
        private string statusCodeField;
        
        private string statusNameField;
        
        private string statusDescriptionField;
        
        private string statusReasonCodeField;
        
        private ChequeSerialDTO[] lstChequeSerialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestCode {
            get {
                return this.requestCodeField;
            }
            set {
                this.requestCodeField = value;
                this.RaisePropertyChanged("RequestCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Shebaa {
            get {
                return this.shebaaField;
            }
            set {
                this.shebaaField = value;
                this.RaisePropertyChanged("Shebaa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StatusName {
            get {
                return this.statusNameField;
            }
            set {
                this.statusNameField = value;
                this.RaisePropertyChanged("StatusName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
                this.RaisePropertyChanged("StatusDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StatusReasonCode {
            get {
                return this.statusReasonCodeField;
            }
            set {
                this.statusReasonCodeField = value;
                this.RaisePropertyChanged("StatusReasonCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public ChequeSerialDTO[] LstChequeSerial {
            get {
                return this.lstChequeSerialField;
            }
            set {
                this.lstChequeSerialField = value;
                this.RaisePropertyChanged("LstChequeSerial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChequeSerialDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int serialNoField;
        
        private string chequeSerialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
                this.RaisePropertyChanged("SerialNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ChequeSerial {
            get {
                return this.chequeSerialField;
            }
            set {
                this.chequeSerialField = value;
                this.RaisePropertyChanged("ChequeSerial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChequeBookStatusList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double errorCodeField;
        
        private string errorDescriptionField;
        
        private ChequeBookStatusDTO[] lstChequeBookStatusDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("ErrorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public ChequeBookStatusDTO[] LstChequeBookStatusDTO {
            get {
                return this.lstChequeBookStatusDTOField;
            }
            set {
                this.lstChequeBookStatusDTOField = value;
                this.RaisePropertyChanged("LstChequeBookStatusDTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChequeBookStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string shebaField;
        
        private string statusCodeField;
        
        private string statusNameField;
        
        private string statusDescriptionField;
        
        private ChequeSerialDTO[] lstChequeSerialField;
        
        private double errorCodeField;
        
        private string errorDescriptionField;
        
        private string statusReasonCodeField;
        
        private int printeryStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sheba {
            get {
                return this.shebaField;
            }
            set {
                this.shebaField = value;
                this.RaisePropertyChanged("Sheba");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StatusName {
            get {
                return this.statusNameField;
            }
            set {
                this.statusNameField = value;
                this.RaisePropertyChanged("StatusName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
                this.RaisePropertyChanged("StatusDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public ChequeSerialDTO[] LstChequeSerial {
            get {
                return this.lstChequeSerialField;
            }
            set {
                this.lstChequeSerialField = value;
                this.RaisePropertyChanged("LstChequeSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("ErrorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string StatusReasonCode {
            get {
                return this.statusReasonCodeField;
            }
            set {
                this.statusReasonCodeField = value;
                this.RaisePropertyChanged("StatusReasonCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int PrinteryStatus {
            get {
                return this.printeryStatusField;
            }
            set {
                this.printeryStatusField = value;
                this.RaisePropertyChanged("PrinteryStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetChequeBookStatusByInquiryCode", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetChequeBookStatusByInquiryCodeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RequestCode;
        
        public GetChequeBookStatusByInquiryCodeRequest() {
        }
        
        public GetChequeBookStatusByInquiryCodeRequest(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string RequestCode) {
            this.AuthHeader = AuthHeader;
            this.RequestCode = RequestCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetChequeBookStatusByInquiryCodeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetChequeBookStatusByInquiryCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RahyabServices.Business.Facades.Sayad.ChequeBookStatus GetChequeBookStatusByInquiryCodeResult;
        
        public GetChequeBookStatusByInquiryCodeResponse() {
        }
        
        public GetChequeBookStatusByInquiryCodeResponse(RahyabServices.Business.Facades.Sayad.ChequeBookStatus GetChequeBookStatusByInquiryCodeResult) {
            this.GetChequeBookStatusByInquiryCodeResult = GetChequeBookStatusByInquiryCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListChequeBookStatusByChequeStatusType", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetListChequeBookStatusByChequeStatusTypeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ChequeStatusTypeCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int FromDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int ToDate;
        
        public GetListChequeBookStatusByChequeStatusTypeRequest() {
        }
        
        public GetListChequeBookStatusByChequeStatusTypeRequest(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string ChequeStatusTypeCode, int FromDate, int ToDate) {
            this.AuthHeader = AuthHeader;
            this.ChequeStatusTypeCode = ChequeStatusTypeCode;
            this.FromDate = FromDate;
            this.ToDate = ToDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListChequeBookStatusByChequeStatusTypeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetListChequeBookStatusByChequeStatusTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RahyabServices.Business.Facades.Sayad.ChequeBookStatusList GetListChequeBookStatusByChequeStatusTypeResult;
        
        public GetListChequeBookStatusByChequeStatusTypeResponse() {
        }
        
        public GetListChequeBookStatusByChequeStatusTypeResponse(RahyabServices.Business.Facades.Sayad.ChequeBookStatusList GetListChequeBookStatusByChequeStatusTypeResult) {
            this.GetListChequeBookStatusByChequeStatusTypeResult = GetListChequeBookStatusByChequeStatusTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertChequeBookRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertChequeBookRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RahyabServices.Business.Facades.Sayad.ChequeBookRequestDTO chequeRequestDTO;
        
        public InsertChequeBookRequestRequest() {
        }
        
        public InsertChequeBookRequestRequest(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, RahyabServices.Business.Facades.Sayad.ChequeBookRequestDTO chequeRequestDTO) {
            this.AuthHeader = AuthHeader;
            this.chequeRequestDTO = chequeRequestDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertChequeBookRequestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertChequeBookRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RahyabServices.Business.Facades.Sayad.RequestResponse InsertChequeBookRequestResult;
        
        public InsertChequeBookRequestResponse() {
        }
        
        public InsertChequeBookRequestResponse(RahyabServices.Business.Facades.Sayad.RequestResponse InsertChequeBookRequestResult) {
            this.InsertChequeBookRequestResult = InsertChequeBookRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateAcceptInquiry", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateAcceptInquiryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RequestCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string InquiryTypeCode;
        
        public UpdateAcceptInquiryRequest() {
        }
        
        public UpdateAcceptInquiryRequest(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string RequestCode, string InquiryTypeCode) {
            this.AuthHeader = AuthHeader;
            this.RequestCode = RequestCode;
            this.InquiryTypeCode = InquiryTypeCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateAcceptInquiryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateAcceptInquiryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RahyabServices.Business.Facades.Sayad.ExceptionFields UpdateAcceptInquiryResult;
        
        public UpdateAcceptInquiryResponse() {
        }
        
        public UpdateAcceptInquiryResponse(RahyabServices.Business.Facades.Sayad.ExceptionFields UpdateAcceptInquiryResult) {
            this.UpdateAcceptInquiryResult = UpdateAcceptInquiryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRejectInquiry", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRejectInquiryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string RequestCode;
        
        public UpdateRejectInquiryRequest() {
        }
        
        public UpdateRejectInquiryRequest(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string RequestCode) {
            this.AuthHeader = AuthHeader;
            this.RequestCode = RequestCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRejectInquiryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRejectInquiryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RahyabServices.Business.Facades.Sayad.ExceptionFields UpdateRejectInquiryResult;
        
        public UpdateRejectInquiryResponse() {
        }
        
        public UpdateRejectInquiryResponse(RahyabServices.Business.Facades.Sayad.ExceptionFields UpdateRejectInquiryResult) {
            this.UpdateRejectInquiryResult = UpdateRejectInquiryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateBaseIBAN", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeactivateBaseIBANRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string IBAN;
        
        public DeactivateBaseIBANRequest() {
        }
        
        public DeactivateBaseIBANRequest(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string IBAN) {
            this.AuthHeader = AuthHeader;
            this.IBAN = IBAN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateBaseIBANResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeactivateBaseIBANResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RahyabServices.Business.Facades.Sayad.ExceptionFields DeactivateBaseIBANResult;
        
        public DeactivateBaseIBANResponse() {
        }
        
        public DeactivateBaseIBANResponse(RahyabServices.Business.Facades.Sayad.ExceptionFields DeactivateBaseIBANResult) {
            this.DeactivateBaseIBANResult = DeactivateBaseIBANResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetChequeAndDebtInquiry", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetChequeAndDebtInquiryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ChequeSerial;
        
        public GetChequeAndDebtInquiryRequest() {
        }
        
        public GetChequeAndDebtInquiryRequest(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string ChequeSerial) {
            this.AuthHeader = AuthHeader;
            this.ChequeSerial = ChequeSerial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetChequeAndDebtInquiryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetChequeAndDebtInquiryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RahyabServices.Business.Facades.Sayad.ChequeInquiryStatus GetChequeAndDebtInquiryResult;
        
        public GetChequeAndDebtInquiryResponse() {
        }
        
        public GetChequeAndDebtInquiryResponse(RahyabServices.Business.Facades.Sayad.ChequeInquiryStatus GetChequeAndDebtInquiryResult) {
            this.GetChequeAndDebtInquiryResult = GetChequeAndDebtInquiryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateChangePassword", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateChangePasswordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string NewPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ConfirmNewPassword;
        
        public UpdateChangePasswordRequest() {
        }
        
        public UpdateChangePasswordRequest(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string NewPassword, string ConfirmNewPassword) {
            this.AuthHeader = AuthHeader;
            this.NewPassword = NewPassword;
            this.ConfirmNewPassword = ConfirmNewPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateChangePasswordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RahyabServices.Business.Facades.Sayad.ExceptionFields UpdateChangePasswordResult;
        
        public UpdateChangePasswordResponse() {
        }
        
        public UpdateChangePasswordResponse(RahyabServices.Business.Facades.Sayad.ExceptionFields UpdateChangePasswordResult) {
            this.UpdateChangePasswordResult = UpdateChangePasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SayadServicesSoapChannel : RahyabServices.Business.Facades.Sayad.SayadServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SayadServicesSoapClient : System.ServiceModel.ClientBase<RahyabServices.Business.Facades.Sayad.SayadServicesSoap>, RahyabServices.Business.Facades.Sayad.SayadServicesSoap {
        
        public SayadServicesSoapClient() {
        }
        
        public SayadServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SayadServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SayadServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SayadServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RahyabServices.Business.Facades.Sayad.GetChequeBookStatusByInquiryCodeResponse RahyabServices.Business.Facades.Sayad.SayadServicesSoap.GetChequeBookStatusByInquiryCode(RahyabServices.Business.Facades.Sayad.GetChequeBookStatusByInquiryCodeRequest request) {
            return base.Channel.GetChequeBookStatusByInquiryCode(request);
        }
        
        public RahyabServices.Business.Facades.Sayad.ChequeBookStatus GetChequeBookStatusByInquiryCode(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string RequestCode) {
            RahyabServices.Business.Facades.Sayad.GetChequeBookStatusByInquiryCodeRequest inValue = new RahyabServices.Business.Facades.Sayad.GetChequeBookStatusByInquiryCodeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.RequestCode = RequestCode;
            RahyabServices.Business.Facades.Sayad.GetChequeBookStatusByInquiryCodeResponse retVal = ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).GetChequeBookStatusByInquiryCode(inValue);
            return retVal.GetChequeBookStatusByInquiryCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.GetChequeBookStatusByInquiryCodeResponse> RahyabServices.Business.Facades.Sayad.SayadServicesSoap.GetChequeBookStatusByInquiryCodeAsync(RahyabServices.Business.Facades.Sayad.GetChequeBookStatusByInquiryCodeRequest request) {
            return base.Channel.GetChequeBookStatusByInquiryCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.GetChequeBookStatusByInquiryCodeResponse> GetChequeBookStatusByInquiryCodeAsync(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string RequestCode) {
            RahyabServices.Business.Facades.Sayad.GetChequeBookStatusByInquiryCodeRequest inValue = new RahyabServices.Business.Facades.Sayad.GetChequeBookStatusByInquiryCodeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.RequestCode = RequestCode;
            return ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).GetChequeBookStatusByInquiryCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RahyabServices.Business.Facades.Sayad.GetListChequeBookStatusByChequeStatusTypeResponse RahyabServices.Business.Facades.Sayad.SayadServicesSoap.GetListChequeBookStatusByChequeStatusType(RahyabServices.Business.Facades.Sayad.GetListChequeBookStatusByChequeStatusTypeRequest request) {
            return base.Channel.GetListChequeBookStatusByChequeStatusType(request);
        }
        
        public RahyabServices.Business.Facades.Sayad.ChequeBookStatusList GetListChequeBookStatusByChequeStatusType(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string ChequeStatusTypeCode, int FromDate, int ToDate) {
            RahyabServices.Business.Facades.Sayad.GetListChequeBookStatusByChequeStatusTypeRequest inValue = new RahyabServices.Business.Facades.Sayad.GetListChequeBookStatusByChequeStatusTypeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ChequeStatusTypeCode = ChequeStatusTypeCode;
            inValue.FromDate = FromDate;
            inValue.ToDate = ToDate;
            RahyabServices.Business.Facades.Sayad.GetListChequeBookStatusByChequeStatusTypeResponse retVal = ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).GetListChequeBookStatusByChequeStatusType(inValue);
            return retVal.GetListChequeBookStatusByChequeStatusTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.GetListChequeBookStatusByChequeStatusTypeResponse> RahyabServices.Business.Facades.Sayad.SayadServicesSoap.GetListChequeBookStatusByChequeStatusTypeAsync(RahyabServices.Business.Facades.Sayad.GetListChequeBookStatusByChequeStatusTypeRequest request) {
            return base.Channel.GetListChequeBookStatusByChequeStatusTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.GetListChequeBookStatusByChequeStatusTypeResponse> GetListChequeBookStatusByChequeStatusTypeAsync(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string ChequeStatusTypeCode, int FromDate, int ToDate) {
            RahyabServices.Business.Facades.Sayad.GetListChequeBookStatusByChequeStatusTypeRequest inValue = new RahyabServices.Business.Facades.Sayad.GetListChequeBookStatusByChequeStatusTypeRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ChequeStatusTypeCode = ChequeStatusTypeCode;
            inValue.FromDate = FromDate;
            inValue.ToDate = ToDate;
            return ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).GetListChequeBookStatusByChequeStatusTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RahyabServices.Business.Facades.Sayad.InsertChequeBookRequestResponse RahyabServices.Business.Facades.Sayad.SayadServicesSoap.InsertChequeBookRequest(RahyabServices.Business.Facades.Sayad.InsertChequeBookRequestRequest request) {
            return base.Channel.InsertChequeBookRequest(request);
        }
        
        public RahyabServices.Business.Facades.Sayad.RequestResponse InsertChequeBookRequest(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, RahyabServices.Business.Facades.Sayad.ChequeBookRequestDTO chequeRequestDTO) {
            RahyabServices.Business.Facades.Sayad.InsertChequeBookRequestRequest inValue = new RahyabServices.Business.Facades.Sayad.InsertChequeBookRequestRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.chequeRequestDTO = chequeRequestDTO;
            RahyabServices.Business.Facades.Sayad.InsertChequeBookRequestResponse retVal = ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).InsertChequeBookRequest(inValue);
            return retVal.InsertChequeBookRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.InsertChequeBookRequestResponse> RahyabServices.Business.Facades.Sayad.SayadServicesSoap.InsertChequeBookRequestAsync(RahyabServices.Business.Facades.Sayad.InsertChequeBookRequestRequest request) {
            return base.Channel.InsertChequeBookRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.InsertChequeBookRequestResponse> InsertChequeBookRequestAsync(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, RahyabServices.Business.Facades.Sayad.ChequeBookRequestDTO chequeRequestDTO) {
            RahyabServices.Business.Facades.Sayad.InsertChequeBookRequestRequest inValue = new RahyabServices.Business.Facades.Sayad.InsertChequeBookRequestRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.chequeRequestDTO = chequeRequestDTO;
            return ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).InsertChequeBookRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RahyabServices.Business.Facades.Sayad.UpdateAcceptInquiryResponse RahyabServices.Business.Facades.Sayad.SayadServicesSoap.UpdateAcceptInquiry(RahyabServices.Business.Facades.Sayad.UpdateAcceptInquiryRequest request) {
            return base.Channel.UpdateAcceptInquiry(request);
        }
        
        public RahyabServices.Business.Facades.Sayad.ExceptionFields UpdateAcceptInquiry(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string RequestCode, string InquiryTypeCode) {
            RahyabServices.Business.Facades.Sayad.UpdateAcceptInquiryRequest inValue = new RahyabServices.Business.Facades.Sayad.UpdateAcceptInquiryRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.RequestCode = RequestCode;
            inValue.InquiryTypeCode = InquiryTypeCode;
            RahyabServices.Business.Facades.Sayad.UpdateAcceptInquiryResponse retVal = ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).UpdateAcceptInquiry(inValue);
            return retVal.UpdateAcceptInquiryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.UpdateAcceptInquiryResponse> RahyabServices.Business.Facades.Sayad.SayadServicesSoap.UpdateAcceptInquiryAsync(RahyabServices.Business.Facades.Sayad.UpdateAcceptInquiryRequest request) {
            return base.Channel.UpdateAcceptInquiryAsync(request);
        }
        
        public System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.UpdateAcceptInquiryResponse> UpdateAcceptInquiryAsync(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string RequestCode, string InquiryTypeCode) {
            RahyabServices.Business.Facades.Sayad.UpdateAcceptInquiryRequest inValue = new RahyabServices.Business.Facades.Sayad.UpdateAcceptInquiryRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.RequestCode = RequestCode;
            inValue.InquiryTypeCode = InquiryTypeCode;
            return ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).UpdateAcceptInquiryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RahyabServices.Business.Facades.Sayad.UpdateRejectInquiryResponse RahyabServices.Business.Facades.Sayad.SayadServicesSoap.UpdateRejectInquiry(RahyabServices.Business.Facades.Sayad.UpdateRejectInquiryRequest request) {
            return base.Channel.UpdateRejectInquiry(request);
        }
        
        public RahyabServices.Business.Facades.Sayad.ExceptionFields UpdateRejectInquiry(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string RequestCode) {
            RahyabServices.Business.Facades.Sayad.UpdateRejectInquiryRequest inValue = new RahyabServices.Business.Facades.Sayad.UpdateRejectInquiryRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.RequestCode = RequestCode;
            RahyabServices.Business.Facades.Sayad.UpdateRejectInquiryResponse retVal = ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).UpdateRejectInquiry(inValue);
            return retVal.UpdateRejectInquiryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.UpdateRejectInquiryResponse> RahyabServices.Business.Facades.Sayad.SayadServicesSoap.UpdateRejectInquiryAsync(RahyabServices.Business.Facades.Sayad.UpdateRejectInquiryRequest request) {
            return base.Channel.UpdateRejectInquiryAsync(request);
        }
        
        public System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.UpdateRejectInquiryResponse> UpdateRejectInquiryAsync(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string RequestCode) {
            RahyabServices.Business.Facades.Sayad.UpdateRejectInquiryRequest inValue = new RahyabServices.Business.Facades.Sayad.UpdateRejectInquiryRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.RequestCode = RequestCode;
            return ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).UpdateRejectInquiryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RahyabServices.Business.Facades.Sayad.DeactivateBaseIBANResponse RahyabServices.Business.Facades.Sayad.SayadServicesSoap.DeactivateBaseIBAN(RahyabServices.Business.Facades.Sayad.DeactivateBaseIBANRequest request) {
            return base.Channel.DeactivateBaseIBAN(request);
        }
        
        public RahyabServices.Business.Facades.Sayad.ExceptionFields DeactivateBaseIBAN(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string IBAN) {
            RahyabServices.Business.Facades.Sayad.DeactivateBaseIBANRequest inValue = new RahyabServices.Business.Facades.Sayad.DeactivateBaseIBANRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.IBAN = IBAN;
            RahyabServices.Business.Facades.Sayad.DeactivateBaseIBANResponse retVal = ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).DeactivateBaseIBAN(inValue);
            return retVal.DeactivateBaseIBANResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.DeactivateBaseIBANResponse> RahyabServices.Business.Facades.Sayad.SayadServicesSoap.DeactivateBaseIBANAsync(RahyabServices.Business.Facades.Sayad.DeactivateBaseIBANRequest request) {
            return base.Channel.DeactivateBaseIBANAsync(request);
        }
        
        public System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.DeactivateBaseIBANResponse> DeactivateBaseIBANAsync(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string IBAN) {
            RahyabServices.Business.Facades.Sayad.DeactivateBaseIBANRequest inValue = new RahyabServices.Business.Facades.Sayad.DeactivateBaseIBANRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.IBAN = IBAN;
            return ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).DeactivateBaseIBANAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RahyabServices.Business.Facades.Sayad.GetChequeAndDebtInquiryResponse RahyabServices.Business.Facades.Sayad.SayadServicesSoap.GetChequeAndDebtInquiry(RahyabServices.Business.Facades.Sayad.GetChequeAndDebtInquiryRequest request) {
            return base.Channel.GetChequeAndDebtInquiry(request);
        }
        
        public RahyabServices.Business.Facades.Sayad.ChequeInquiryStatus GetChequeAndDebtInquiry(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string ChequeSerial) {
            RahyabServices.Business.Facades.Sayad.GetChequeAndDebtInquiryRequest inValue = new RahyabServices.Business.Facades.Sayad.GetChequeAndDebtInquiryRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ChequeSerial = ChequeSerial;
            RahyabServices.Business.Facades.Sayad.GetChequeAndDebtInquiryResponse retVal = ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).GetChequeAndDebtInquiry(inValue);
            return retVal.GetChequeAndDebtInquiryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.GetChequeAndDebtInquiryResponse> RahyabServices.Business.Facades.Sayad.SayadServicesSoap.GetChequeAndDebtInquiryAsync(RahyabServices.Business.Facades.Sayad.GetChequeAndDebtInquiryRequest request) {
            return base.Channel.GetChequeAndDebtInquiryAsync(request);
        }
        
        public System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.GetChequeAndDebtInquiryResponse> GetChequeAndDebtInquiryAsync(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string ChequeSerial) {
            RahyabServices.Business.Facades.Sayad.GetChequeAndDebtInquiryRequest inValue = new RahyabServices.Business.Facades.Sayad.GetChequeAndDebtInquiryRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.ChequeSerial = ChequeSerial;
            return ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).GetChequeAndDebtInquiryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RahyabServices.Business.Facades.Sayad.UpdateChangePasswordResponse RahyabServices.Business.Facades.Sayad.SayadServicesSoap.UpdateChangePassword(RahyabServices.Business.Facades.Sayad.UpdateChangePasswordRequest request) {
            return base.Channel.UpdateChangePassword(request);
        }
        
        public RahyabServices.Business.Facades.Sayad.ExceptionFields UpdateChangePassword(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string NewPassword, string ConfirmNewPassword) {
            RahyabServices.Business.Facades.Sayad.UpdateChangePasswordRequest inValue = new RahyabServices.Business.Facades.Sayad.UpdateChangePasswordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.NewPassword = NewPassword;
            inValue.ConfirmNewPassword = ConfirmNewPassword;
            RahyabServices.Business.Facades.Sayad.UpdateChangePasswordResponse retVal = ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).UpdateChangePassword(inValue);
            return retVal.UpdateChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.UpdateChangePasswordResponse> RahyabServices.Business.Facades.Sayad.SayadServicesSoap.UpdateChangePasswordAsync(RahyabServices.Business.Facades.Sayad.UpdateChangePasswordRequest request) {
            return base.Channel.UpdateChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<RahyabServices.Business.Facades.Sayad.UpdateChangePasswordResponse> UpdateChangePasswordAsync(RahyabServices.Business.Facades.Sayad.AuthHeader AuthHeader, string NewPassword, string ConfirmNewPassword) {
            RahyabServices.Business.Facades.Sayad.UpdateChangePasswordRequest inValue = new RahyabServices.Business.Facades.Sayad.UpdateChangePasswordRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.NewPassword = NewPassword;
            inValue.ConfirmNewPassword = ConfirmNewPassword;
            return ((RahyabServices.Business.Facades.Sayad.SayadServicesSoap)(this)).UpdateChangePasswordAsync(inValue);
        }
    }
}
