using RahyabServices.Common.Dto;
namespace RahyabServices.Business.Dtos.VipBanking{
    public class GeneralReportDto : IDto{
        public int? CountAllBankCusts { get; set; }
        public int? CountRealCusts { get; set; }
        public string CUSTYPE { get; set; }
        public long? CountLegalCusts { get; set; }
        public int? CountVipI { get; set; }
        public string PrivateCustomerLevel { get; set; }
        public decimal? CurrentRemainingCustomerVipI { get; set; }
        public decimal? MeanTurnoverVipI { get; set; }
        public int? CountSharedCusts { get; set; }
        public int? CountVipII { get; set; }
        public decimal? CurrentRemainingCustomerVipII { get; set; }
        public decimal? MeanTurnoverVipII { get; set; }
        public int? CountVipIII { get; set; }
        public int? CountPrivate { get; set; }
        public int? Upgraded { get; set; }
        public int? Downgraded { get; set; }
        public int? PotentialCount { get; set; }
        public decimal? MeanTurnoverPrivate { get; set; }
        public decimal? CurrentRemainingCustomerVipIII { get; set; }
        public decimal? CurrentRemainingCustomerPrivate { get; set; }
        public decimal? MeanTurnoverVipIII { get; set; }
        public long? AllCashBank { get; set; }
        public int? CountAllVip { get; set; }
        public int? RatioCountDowngrade { get; set; }
        public int? RatioCountUpgrade { get; set; }
        public int? RatioCountVipIDivAllVip { get; set; }
        public int? RatioCountVipIIDivAllVip { get; set; }
        public int? RatioCountVipIIIDivAllVip { get; set; }
        public int? RationCountPrivateDivAllVip { get; set; }
        public int? RatioCountVipIDivAll { get; set; }
        public int? RatioCountVipIIDivAll { get; set; }
        public int? RatioCountVipIIIDivAll { get; set; }
        public int? RatioCountPrivateDivAll { get; set; }
        public decimal? RatioCashVipIDivAllVip { get; set; }
        public decimal? RatioCashVipIIDivAllVip { get; set; }
        public decimal? RatioCashVipIIIDivAllVip { get; set; }
        public decimal? RatioCashPrivateDivAllVip { get; set; }
        public decimal? RatioCashVipIDivAll { get; set; }
        public decimal? RatioCashVipIIDivAll { get; set; }
        public decimal? RatioCashVipIIIDivAll { get; set; }
        public decimal? RatioCashPrivateDivAll { get; set; }
        public decimal? AllCashVip { get; set; }
        public long? CountSumRealVsLegalCusts { get; set; }
        public long? CountSumRealVsLegalVsSharedCusts { get; set; }
        public int? CountSumRealVsSharedCusts { get; set; }
        public int? RatioCountVipIDivSumRealVsShared { get; set; }
        public int? RatioCountVipIIDivSumRealVsShared { get; set; }
        public int? RatioCountVipIIIDivSumRealVsShared { get; set; }
        public int? RatioCountPrivateDivSumRealVsShared { get; set; }
        public long? RatioCountVipIDivSumRealVsSharedVsLegal { get; set; }
        public long? RatioCountVipIIDivSumRealVsSharedVsLegal { get; set; }
        public long? RatioCountVipIIIDivSumRealVsSharedVsLegal { get; set; }
        public long? RatioCountPrivateDivSumRealVsSharedVsLegal { get; set; }
        public int? RatioAllVipDivSumRealVsShared { get; set; }
        public long? RatioAllVipDivSumRealVsSharedVsLegal { get; set; }
        public int? RatioUpgradeDivSumRealVsShared { get; set; }
        public int? RatioUpgradeDivSumRealVsSharedVsLegal { get; set; }
        public int? RatioDowngradeDivSumRealVsShared { get; set; }
        public int? RatioDowngradeDivSumRealVsSharedVsLegal { get; set; }
        public int? RatioPotentialDivSumAllBank { get; set; }
        public int? RatioPotentialDivSumRealVsShared { get; set; }
        public int? RatioPotentialDivSumRealVsSharedVsLegal { get; set; }
        public long KeyId { get; set; }
    }
}