using RahyabServices.Common.Dto;
namespace RahyabServices.Business.Dtos.VipBanking{
    public class GeneralReportDto : IDto{
        public int? CountAllBankCusts { get; set; }
        public int? CountRealCusts { get; set; }
        public string CUSTYPE { get; set; }
        public long? CountLegalCusts { get; set; }
        public int? CountVipI { get; set; }
        public string PrivateCustomerLevel { get; set; }
        public long? CurrentRemainingCustomerVipI { get; set; }
        public decimal? MeanTurnoverVipI { get; set; }
        public int? CountSharedCusts { get; set; }
        public int? CountVipII { get; set; }
        public long? CurrentRemainingCustomerVipII { get; set; }
        public decimal? MeanTurnoverVipII { get; set; }
        public int? CountVipIII { get; set; }
        public int? CountPrivate { get; set; }
        public int? Upgraded { get; set; }
        public int? Downgraded { get; set; }
        public int? PotentialCount { get; set; }
        public decimal? MeanTurnoverPrivate { get; set; }
        public long? CurrentRemainingCustomerVipIII { get; set; }
        public decimal? CurrentRemainingCustomerPrivate { get; set; }
        public decimal? MeanTurnoverVipIII { get; set; }
        public long? AllCashBank { get; set; }
        public long KeyId { get; set; }
        public int? CountAllVip { get; set; }
        public string RatioCountDowngrade { get; set; }
        public string RatioCountUpgrade { get; set; }
        public string RatioCountVipIDivAllVip { get; set; }
        public string RatioCountVipIIDivAllVip { get; set; }
        public string RatioCountVipIIIDivAllVip { get; set; }
        public string RationCountPrivateDivAllVip { get; set; }
        public string RatioCountVipIDivAll { get; set; }
        public string RatioCountVipIIDivAll { get; set; }
        public string RatioCountVipIIIDivAll { get; set; }
        public string RatioCountPrivateDivAll { get; set; }
        public long? CountSumRealVsLegalCusts { get; set; }
        public long? CountSumRealVsLegalVsSharedCusts { get; set; }
        public int? CountSumRealVsSharedCusts { get; set; }
        public string RatioCountPrivateDivSumRealVsShared { get; set; }
        public string RatioCountVipIDivSumRealVsShared { get; set; }
        public string RatioCountVipIIDivSumRealVsShared { get; set; }
        public string RatioCountVipIIIDivSumRealVsShared { get; set; }
        public string RatioCountVipIDivSumRealVsSharedVsLegal { get; set; }
        public string RatioCountVipIIDivSumRealVsSharedVsLegal { get; set; }
        public string RatioCountVipIIIDivSumRealVsSharedVsLegal { get; set; }
        public string RatioCountPrivateDivSumRealVsSharedVsLegal { get; set; }
        public string RatioAllVipDivSumRealVsShared { get; set; }
        public string RatioAllVipDivSumRealVsSharedVsLegal { get; set; }
        public string RatioUpgradeDivSumRealVsShared { get; set; }
        public string RatioUpgradeDivSumRealVsSharedVsLegal { get; set; }
        public string RatioDowngradeDivSumRealVsShared { get; set; }
        public string RatioDowngradeDivSumRealVsSharedVsLegal { get; set; }
        public string RatioPotentialDivSumAllBank { get; set; }
        public string RatioPotentialDivSumRealVsShared { get; set; }
        public string RatioPotentialDivSumRealVsSharedVsLegal { get; set; }
        public decimal? AllCashVip { get; set; }
        public string RatioCashVipIIDivAll { get; set; }
        public string RatioCashVipIDivAll { get; set; }
        public string RatioCashVipIIIDivAll { get; set; }
        public decimal? RatioCashPrivateDivAll { get; set; }
        public string RatioCashVipIDivAllVip { get; set; }
        public string RatioCashVipIIDivAllVip { get; set; }
        public string RatioCashVipIIIDivAllVip { get; set; }
        public string RatioCashPrivateDivAllVip { get; set; }
    }
}