//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RahyabServices.Business.Facades.SayadWebRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SayadServicesSoap", Namespace="http://tempuri.org/")]
    public partial class SayadServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetChequeBookStatusByInquiryCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertChequeBookRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateAcceptInquiryOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateRejectInquiryOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeactivateBaseIBANOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChequeAndDebtInquiryOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateChangePasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SayadServices() {
            this.Url = global::RahyabServices.Business.Facades.Properties.Settings.Default.RahyabServices_Business_Facades_SayadWebRef_SayadServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetChequeBookStatusByInquiryCodeCompletedEventHandler GetChequeBookStatusByInquiryCodeCompleted;
        
        /// <remarks/>
        public event InsertChequeBookRequestCompletedEventHandler InsertChequeBookRequestCompleted;
        
        /// <remarks/>
        public event UpdateAcceptInquiryCompletedEventHandler UpdateAcceptInquiryCompleted;
        
        /// <remarks/>
        public event UpdateRejectInquiryCompletedEventHandler UpdateRejectInquiryCompleted;
        
        /// <remarks/>
        public event DeactivateBaseIBANCompletedEventHandler DeactivateBaseIBANCompleted;
        
        /// <remarks/>
        public event GetChequeAndDebtInquiryCompletedEventHandler GetChequeAndDebtInquiryCompleted;
        
        /// <remarks/>
        public event UpdateChangePasswordCompletedEventHandler UpdateChangePasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetChequeBookStatusByInquiryCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChequeBookStatus GetChequeBookStatusByInquiryCode(string RequestCode) {
            object[] results = this.Invoke("GetChequeBookStatusByInquiryCode", new object[] {
                        RequestCode});
            return ((ChequeBookStatus)(results[0]));
        }
        
        /// <remarks/>
        public void GetChequeBookStatusByInquiryCodeAsync(string RequestCode) {
            this.GetChequeBookStatusByInquiryCodeAsync(RequestCode, null);
        }
        
        /// <remarks/>
        public void GetChequeBookStatusByInquiryCodeAsync(string RequestCode, object userState) {
            if ((this.GetChequeBookStatusByInquiryCodeOperationCompleted == null)) {
                this.GetChequeBookStatusByInquiryCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChequeBookStatusByInquiryCodeOperationCompleted);
            }
            this.InvokeAsync("GetChequeBookStatusByInquiryCode", new object[] {
                        RequestCode}, this.GetChequeBookStatusByInquiryCodeOperationCompleted, userState);
        }
        
        private void OnGetChequeBookStatusByInquiryCodeOperationCompleted(object arg) {
            if ((this.GetChequeBookStatusByInquiryCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChequeBookStatusByInquiryCodeCompleted(this, new GetChequeBookStatusByInquiryCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertChequeBookRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RequestResponse InsertChequeBookRequest(ChequeBookRequestDTO chequeRequestDTO) {
            object[] results = this.Invoke("InsertChequeBookRequest", new object[] {
                        chequeRequestDTO});
            return ((RequestResponse)(results[0]));
        }
        
        /// <remarks/>
        public void InsertChequeBookRequestAsync(ChequeBookRequestDTO chequeRequestDTO) {
            this.InsertChequeBookRequestAsync(chequeRequestDTO, null);
        }
        
        /// <remarks/>
        public void InsertChequeBookRequestAsync(ChequeBookRequestDTO chequeRequestDTO, object userState) {
            if ((this.InsertChequeBookRequestOperationCompleted == null)) {
                this.InsertChequeBookRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertChequeBookRequestOperationCompleted);
            }
            this.InvokeAsync("InsertChequeBookRequest", new object[] {
                        chequeRequestDTO}, this.InsertChequeBookRequestOperationCompleted, userState);
        }
        
        private void OnInsertChequeBookRequestOperationCompleted(object arg) {
            if ((this.InsertChequeBookRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertChequeBookRequestCompleted(this, new InsertChequeBookRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateAcceptInquiry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExceptionFields UpdateAcceptInquiry(string RequestCode, string InquiryTypeCode) {
            object[] results = this.Invoke("UpdateAcceptInquiry", new object[] {
                        RequestCode,
                        InquiryTypeCode});
            return ((ExceptionFields)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAcceptInquiryAsync(string RequestCode, string InquiryTypeCode) {
            this.UpdateAcceptInquiryAsync(RequestCode, InquiryTypeCode, null);
        }
        
        /// <remarks/>
        public void UpdateAcceptInquiryAsync(string RequestCode, string InquiryTypeCode, object userState) {
            if ((this.UpdateAcceptInquiryOperationCompleted == null)) {
                this.UpdateAcceptInquiryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateAcceptInquiryOperationCompleted);
            }
            this.InvokeAsync("UpdateAcceptInquiry", new object[] {
                        RequestCode,
                        InquiryTypeCode}, this.UpdateAcceptInquiryOperationCompleted, userState);
        }
        
        private void OnUpdateAcceptInquiryOperationCompleted(object arg) {
            if ((this.UpdateAcceptInquiryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateAcceptInquiryCompleted(this, new UpdateAcceptInquiryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateRejectInquiry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExceptionFields UpdateRejectInquiry(string RequestCode) {
            object[] results = this.Invoke("UpdateRejectInquiry", new object[] {
                        RequestCode});
            return ((ExceptionFields)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateRejectInquiryAsync(string RequestCode) {
            this.UpdateRejectInquiryAsync(RequestCode, null);
        }
        
        /// <remarks/>
        public void UpdateRejectInquiryAsync(string RequestCode, object userState) {
            if ((this.UpdateRejectInquiryOperationCompleted == null)) {
                this.UpdateRejectInquiryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateRejectInquiryOperationCompleted);
            }
            this.InvokeAsync("UpdateRejectInquiry", new object[] {
                        RequestCode}, this.UpdateRejectInquiryOperationCompleted, userState);
        }
        
        private void OnUpdateRejectInquiryOperationCompleted(object arg) {
            if ((this.UpdateRejectInquiryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateRejectInquiryCompleted(this, new UpdateRejectInquiryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeactivateBaseIBAN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExceptionFields DeactivateBaseIBAN(string IBAN) {
            object[] results = this.Invoke("DeactivateBaseIBAN", new object[] {
                        IBAN});
            return ((ExceptionFields)(results[0]));
        }
        
        /// <remarks/>
        public void DeactivateBaseIBANAsync(string IBAN) {
            this.DeactivateBaseIBANAsync(IBAN, null);
        }
        
        /// <remarks/>
        public void DeactivateBaseIBANAsync(string IBAN, object userState) {
            if ((this.DeactivateBaseIBANOperationCompleted == null)) {
                this.DeactivateBaseIBANOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeactivateBaseIBANOperationCompleted);
            }
            this.InvokeAsync("DeactivateBaseIBAN", new object[] {
                        IBAN}, this.DeactivateBaseIBANOperationCompleted, userState);
        }
        
        private void OnDeactivateBaseIBANOperationCompleted(object arg) {
            if ((this.DeactivateBaseIBANCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeactivateBaseIBANCompleted(this, new DeactivateBaseIBANCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetChequeAndDebtInquiry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ChequeInquiryStatus GetChequeAndDebtInquiry(string ChequeSerial) {
            object[] results = this.Invoke("GetChequeAndDebtInquiry", new object[] {
                        ChequeSerial});
            return ((ChequeInquiryStatus)(results[0]));
        }
        
        /// <remarks/>
        public void GetChequeAndDebtInquiryAsync(string ChequeSerial) {
            this.GetChequeAndDebtInquiryAsync(ChequeSerial, null);
        }
        
        /// <remarks/>
        public void GetChequeAndDebtInquiryAsync(string ChequeSerial, object userState) {
            if ((this.GetChequeAndDebtInquiryOperationCompleted == null)) {
                this.GetChequeAndDebtInquiryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChequeAndDebtInquiryOperationCompleted);
            }
            this.InvokeAsync("GetChequeAndDebtInquiry", new object[] {
                        ChequeSerial}, this.GetChequeAndDebtInquiryOperationCompleted, userState);
        }
        
        private void OnGetChequeAndDebtInquiryOperationCompleted(object arg) {
            if ((this.GetChequeAndDebtInquiryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChequeAndDebtInquiryCompleted(this, new GetChequeAndDebtInquiryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateChangePassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExceptionFields UpdateChangePassword(string NewPassword, string ConfirmNewPassword) {
            object[] results = this.Invoke("UpdateChangePassword", new object[] {
                        NewPassword,
                        ConfirmNewPassword});
            return ((ExceptionFields)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateChangePasswordAsync(string NewPassword, string ConfirmNewPassword) {
            this.UpdateChangePasswordAsync(NewPassword, ConfirmNewPassword, null);
        }
        
        /// <remarks/>
        public void UpdateChangePasswordAsync(string NewPassword, string ConfirmNewPassword, object userState) {
            if ((this.UpdateChangePasswordOperationCompleted == null)) {
                this.UpdateChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateChangePasswordOperationCompleted);
            }
            this.InvokeAsync("UpdateChangePassword", new object[] {
                        NewPassword,
                        ConfirmNewPassword}, this.UpdateChangePasswordOperationCompleted, userState);
        }
        
        private void OnUpdateChangePasswordOperationCompleted(object arg) {
            if ((this.UpdateChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateChangePasswordCompleted(this, new UpdateChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonInquiryStatus {
        
        private string nameField;
        
        private string identifierField;
        
        private string idNumField;
        
        private int birthDateField;
        
        private string cityCodeField;
        
        private string returnedChequesField;
        
        private string debtStatusField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string IdNum {
            get {
                return this.idNumField;
            }
            set {
                this.idNumField = value;
            }
        }
        
        /// <remarks/>
        public int BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public string CityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnedCheques {
            get {
                return this.returnedChequesField;
            }
            set {
                this.returnedChequesField = value;
            }
        }
        
        /// <remarks/>
        public string DebtStatus {
            get {
                return this.debtStatusField;
            }
            set {
                this.debtStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChequeInquiryStatus {
        
        private string iBANField;
        
        private PersonInquiryStatus[] accountOwnerInquiryStatusField;
        
        private PersonInquiryStatus[] signatureOwnerInquiryStatusField;
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
        
        /// <remarks/>
        public PersonInquiryStatus[] AccountOwnerInquiryStatus {
            get {
                return this.accountOwnerInquiryStatusField;
            }
            set {
                this.accountOwnerInquiryStatusField = value;
            }
        }
        
        /// <remarks/>
        public PersonInquiryStatus[] SignatureOwnerInquiryStatus {
            get {
                return this.signatureOwnerInquiryStatusField;
            }
            set {
                this.signatureOwnerInquiryStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExceptionFields {
        
        private double codeField;
        
        private string descriptionField;
        
        private string specific1Field;
        
        private string specific2Field;
        
        private string specific3Field;
        
        private string specific4Field;
        
        /// <remarks/>
        public double Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Specific1 {
            get {
                return this.specific1Field;
            }
            set {
                this.specific1Field = value;
            }
        }
        
        /// <remarks/>
        public string Specific2 {
            get {
                return this.specific2Field;
            }
            set {
                this.specific2Field = value;
            }
        }
        
        /// <remarks/>
        public string Specific3 {
            get {
                return this.specific3Field;
            }
            set {
                this.specific3Field = value;
            }
        }
        
        /// <remarks/>
        public string Specific4 {
            get {
                return this.specific4Field;
            }
            set {
                this.specific4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestResponse {
        
        private double codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public double Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SignatureOwnersDTO {
        
        private string descriptionField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string identifierField;
        
        private IdentifierTypeList identifierTypeField;
        
        private string abisIdentifireTypeField;
        
        private string idNumField;
        
        private int birthDateField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierTypeList IdentifierType {
            get {
                return this.identifierTypeField;
            }
            set {
                this.identifierTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AbisIdentifireType {
            get {
                return this.abisIdentifireTypeField;
            }
            set {
                this.abisIdentifireTypeField = value;
            }
        }
        
        /// <remarks/>
        public string IdNum {
            get {
                return this.idNumField;
            }
            set {
                this.idNumField = value;
            }
        }
        
        /// <remarks/>
        public int BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum IdentifierTypeList {
        
        /// <remarks/>
        UnKnown,
        
        /// <remarks/>
        NationalCode,
        
        /// <remarks/>
        NationalID,
        
        /// <remarks/>
        ForeignID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AccountOwnersDTO {
        
        private string descriptionField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string nameField;
        
        private int partyTypeField;
        
        private string identifierField;
        
        private IdentifierTypeList identifierTypeField;
        
        private string abisIdentifireTypeField;
        
        private string idNumField;
        
        private int birthDateField;
        
        private string cityCodeField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int PartyType {
            get {
                return this.partyTypeField;
            }
            set {
                this.partyTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public IdentifierTypeList IdentifierType {
            get {
                return this.identifierTypeField;
            }
            set {
                this.identifierTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AbisIdentifireType {
            get {
                return this.abisIdentifireTypeField;
            }
            set {
                this.abisIdentifireTypeField = value;
            }
        }
        
        /// <remarks/>
        public string IdNum {
            get {
                return this.idNumField;
            }
            set {
                this.idNumField = value;
            }
        }
        
        /// <remarks/>
        public int BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        public string CityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChequeBookRequestDTO {
        
        private string requestCodeField;
        
        private SharedAccountTypes sharedAccountField;
        
        private string bankCodeField;
        
        private string branchCodeField;
        
        private string branchNameField;
        
        private string ownerBranchNameField;
        
        private string ownerBranchCodeField;
        
        private string iBANField;
        
        private int sheetCountField;
        
        private AccountOwnersDTO[] accountOwnersDTOField;
        
        private SignatureOwnersDTO[] signatureOwnersDTOField;
        
        private string postCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string RequestCode {
            get {
                return this.requestCodeField;
            }
            set {
                this.requestCodeField = value;
            }
        }
        
        /// <remarks/>
        public SharedAccountTypes SharedAccount {
            get {
                return this.sharedAccountField;
            }
            set {
                this.sharedAccountField = value;
            }
        }
        
        /// <remarks/>
        public string BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BranchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BranchName {
            get {
                return this.branchNameField;
            }
            set {
                this.branchNameField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerBranchName {
            get {
                return this.ownerBranchNameField;
            }
            set {
                this.ownerBranchNameField = value;
            }
        }
        
        /// <remarks/>
        public string OwnerBranchCode {
            get {
                return this.ownerBranchCodeField;
            }
            set {
                this.ownerBranchCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
        
        /// <remarks/>
        public int SheetCount {
            get {
                return this.sheetCountField;
            }
            set {
                this.sheetCountField = value;
            }
        }
        
        /// <remarks/>
        public AccountOwnersDTO[] AccountOwnersDTO {
            get {
                return this.accountOwnersDTOField;
            }
            set {
                this.accountOwnersDTOField = value;
            }
        }
        
        /// <remarks/>
        public SignatureOwnersDTO[] SignatureOwnersDTO {
            get {
                return this.signatureOwnersDTOField;
            }
            set {
                this.signatureOwnersDTOField = value;
            }
        }
        
        /// <remarks/>
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SharedAccountTypes {
        
        /// <remarks/>
        UnShared,
        
        /// <remarks/>
        Shared,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChequeSerialDTO {
        
        private int serialNoField;
        
        private string chequeSerialField;
        
        /// <remarks/>
        public int SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
            }
        }
        
        /// <remarks/>
        public string ChequeSerial {
            get {
                return this.chequeSerialField;
            }
            set {
                this.chequeSerialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ChequeBookStatus {
        
        private string shebaField;
        
        private string statusCodeField;
        
        private string statusNameField;
        
        private string statusDescriptionField;
        
        private ChequeSerialDTO[] lstChequeSerialField;
        
        private double errorCodeField;
        
        private string errorDescriptionField;
        
        private string statusReasonCodeField;
        
        /// <remarks/>
        public string Sheba {
            get {
                return this.shebaField;
            }
            set {
                this.shebaField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string StatusName {
            get {
                return this.statusNameField;
            }
            set {
                this.statusNameField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public ChequeSerialDTO[] LstChequeSerial {
            get {
                return this.lstChequeSerialField;
            }
            set {
                this.lstChequeSerialField = value;
            }
        }
        
        /// <remarks/>
        public double ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string StatusReasonCode {
            get {
                return this.statusReasonCodeField;
            }
            set {
                this.statusReasonCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetChequeBookStatusByInquiryCodeCompletedEventHandler(object sender, GetChequeBookStatusByInquiryCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChequeBookStatusByInquiryCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChequeBookStatusByInquiryCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChequeBookStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChequeBookStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void InsertChequeBookRequestCompletedEventHandler(object sender, InsertChequeBookRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertChequeBookRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertChequeBookRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RequestResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RequestResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void UpdateAcceptInquiryCompletedEventHandler(object sender, UpdateAcceptInquiryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateAcceptInquiryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateAcceptInquiryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExceptionFields Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExceptionFields)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void UpdateRejectInquiryCompletedEventHandler(object sender, UpdateRejectInquiryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateRejectInquiryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateRejectInquiryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExceptionFields Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExceptionFields)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void DeactivateBaseIBANCompletedEventHandler(object sender, DeactivateBaseIBANCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeactivateBaseIBANCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeactivateBaseIBANCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExceptionFields Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExceptionFields)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetChequeAndDebtInquiryCompletedEventHandler(object sender, GetChequeAndDebtInquiryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChequeAndDebtInquiryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChequeAndDebtInquiryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ChequeInquiryStatus Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ChequeInquiryStatus)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void UpdateChangePasswordCompletedEventHandler(object sender, UpdateChangePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExceptionFields Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExceptionFields)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591